# This rule is not used by the project spring-boot-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the spring.dante-lor.github.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: spring-boot-operator
    app.kubernetes.io/managed-by: kustomize
  name: springbootapplication-editor-role
rules:
- apiGroups:
  - spring.dante-lor.github.io
  resources:
  - springbootapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spring.dante-lor.github.io
  resources:
  - springbootapplications/status
  verbs:
  - get
