# This rule is not used by the project spring-boot-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to spring.dante-lor.github.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: spring-boot-operator
    app.kubernetes.io/managed-by: kustomize
  name: springbootapplication-viewer-role
rules:
- apiGroups:
  - spring.dante-lor.github.io
  resources:
  - springbootapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - spring.dante-lor.github.io
  resources:
  - springbootapplications/status
  verbs:
  - get
