apiVersion: spring.dante-lor.github.io/v1alpha1
kind: SpringBootApplication
metadata:
  labels:
    app.kubernetes.io/name: spring-boot-operator
    app.kubernetes.io/managed-by: kustomize
  name: configured-app
spec:
  image: registry.k8s.io/pause:latest
  config:
    server:
      port: 8000
    spring:
      application:
        name: my-app