apiVersion: spring.dante-lor.github.io/v1alpha1
kind: SpringBootApplication
metadata:
  labels:
    app.kubernetes.io/name: spring-boot-operator
    app.kubernetes.io/managed-by: kustomize
  name: custom-resources
spec:
  image: registry.k8s.io/pause:latest
  resources:
    cpu: 4
    memory: 8Gi