---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: springbootapplications.spring.dante-lor.github.io
spec:
  group: spring.dante-lor.github.io
  names:
    kind: SpringBootApplication
    listKind: SpringBootApplicationList
    plural: springbootapplications
    singular: springbootapplication
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: SpringBootApplication is the Schema for the springbootapplications
          API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: SpringBootApplicationSpec defines the desired state of SpringBootApplication.
            properties:
              autoscaler:
                description: Autoscaling configuration
                properties:
                  behaviour:
                    description: Scaling behaviour
                    properties:
                      scaleDown:
                        description: |-
                          scaleDown is scaling policy for scaling Down.
                          If not set, the default value is to allow to scale down to minReplicas pods, with a
                          300 second stabilization window (i.e., the highest recommendation for
                          the last 300sec is used).
                        properties:
                          policies:
                            description: |-
                              policies is a list of potential scaling polices which can be used during scaling.
                              If not set, use the default values:
                              - For scale up: allow doubling the number of pods, or an absolute change of 4 pods in a 15s window.
                              - For scale down: allow all pods to be removed in a 15s window.
                            items:
                              description: HPAScalingPolicy is a single policy which
                                must hold true for a specified past interval.
                              properties:
                                periodSeconds:
                                  description: |-
                                    periodSeconds specifies the window of time for which the policy should hold true.
                                    PeriodSeconds must be greater than zero and less than or equal to 1800 (30 min).
                                  format: int32
                                  type: integer
                                type:
                                  description: type is used to specify the scaling
                                    policy.
                                  type: string
                                value:
                                  description: |-
                                    value contains the amount of change which is permitted by the policy.
                                    It must be greater than zero
                                  format: int32
                                  type: integer
                              required:
                              - periodSeconds
                              - type
                              - value
                              type: object
                            type: array
                            x-kubernetes-list-type: atomic
                          selectPolicy:
                            description: |-
                              selectPolicy is used to specify which policy should be used.
                              If not set, the default value Max is used.
                            type: string
                          stabilizationWindowSeconds:
                            description: |-
                              stabilizationWindowSeconds is the number of seconds for which past recommendations should be
                              considered while scaling up or scaling down.
                              StabilizationWindowSeconds must be greater than or equal to zero and less than or equal to 3600 (one hour).
                              If not set, use the default values:
                              - For scale up: 0 (i.e. no stabilization is done).
                              - For scale down: 300 (i.e. the stabilization window is 300 seconds long).
                            format: int32
                            type: integer
                          tolerance:
                            anyOf:
                            - type: integer
                            - type: string
                            description: |-
                              tolerance is the tolerance on the ratio between the current and desired
                              metric value under which no updates are made to the desired number of
                              replicas (e.g. 0.01 for 1%). Must be greater than or equal to zero. If not
                              set, the default cluster-wide tolerance is applied (by default 10%).

                              For example, if autoscaling is configured with a memory consumption target of 100Mi,
                              and scale-down and scale-up tolerances of 5% and 1% respectively, scaling will be
                              triggered when the actual consumption falls below 95Mi or exceeds 101Mi.

                              This is an alpha field and requires enabling the HPAConfigurableTolerance
                              feature gate.
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                            x-kubernetes-int-or-string: true
                        type: object
                      scaleUp:
                        description: |-
                          scaleUp is scaling policy for scaling Up.
                          If not set, the default value is the higher of:
                            * increase no more than 4 pods per 60 seconds
                            * double the number of pods per 60 seconds
                          No stabilization is used.
                        properties:
                          policies:
                            description: |-
                              policies is a list of potential scaling polices which can be used during scaling.
                              If not set, use the default values:
                              - For scale up: allow doubling the number of pods, or an absolute change of 4 pods in a 15s window.
                              - For scale down: allow all pods to be removed in a 15s window.
                            items:
                              description: HPAScalingPolicy is a single policy which
                                must hold true for a specified past interval.
                              properties:
                                periodSeconds:
                                  description: |-
                                    periodSeconds specifies the window of time for which the policy should hold true.
                                    PeriodSeconds must be greater than zero and less than or equal to 1800 (30 min).
                                  format: int32
                                  type: integer
                                type:
                                  description: type is used to specify the scaling
                                    policy.
                                  type: string
                                value:
                                  description: |-
                                    value contains the amount of change which is permitted by the policy.
                                    It must be greater than zero
                                  format: int32
                                  type: integer
                              required:
                              - periodSeconds
                              - type
                              - value
                              type: object
                            type: array
                            x-kubernetes-list-type: atomic
                          selectPolicy:
                            description: |-
                              selectPolicy is used to specify which policy should be used.
                              If not set, the default value Max is used.
                            type: string
                          stabilizationWindowSeconds:
                            description: |-
                              stabilizationWindowSeconds is the number of seconds for which past recommendations should be
                              considered while scaling up or scaling down.
                              StabilizationWindowSeconds must be greater than or equal to zero and less than or equal to 3600 (one hour).
                              If not set, use the default values:
                              - For scale up: 0 (i.e. no stabilization is done).
                              - For scale down: 300 (i.e. the stabilization window is 300 seconds long).
                            format: int32
                            type: integer
                          tolerance:
                            anyOf:
                            - type: integer
                            - type: string
                            description: |-
                              tolerance is the tolerance on the ratio between the current and desired
                              metric value under which no updates are made to the desired number of
                              replicas (e.g. 0.01 for 1%). Must be greater than or equal to zero. If not
                              set, the default cluster-wide tolerance is applied (by default 10%).

                              For example, if autoscaling is configured with a memory consumption target of 100Mi,
                              and scale-down and scale-up tolerances of 5% and 1% respectively, scaling will be
                              triggered when the actual consumption falls below 95Mi or exceeds 101Mi.

                              This is an alpha field and requires enabling the HPAConfigurableTolerance
                              feature gate.
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                            x-kubernetes-int-or-string: true
                        type: object
                    type: object
                  maxReplicas:
                    default: 10
                    description: Max replicas
                    type: integer
                  minReplicas:
                    default: 2
                    description: Min replicas
                    type: integer
                  utilizationTarget:
                    description: Utilization target
                    properties:
                      cpuPercentage:
                        description: CPU percentage target
                        format: int32
                        type: integer
                    type: object
                type: object
              config:
                description: Application.yaml file contents
                type: object
                x-kubernetes-preserve-unknown-fields: true
              contextPath:
                default: /
                description: Context path for the application to use
                type: string
              image:
                description: Docker image to run (required)
                minLength: 1
                type: string
              port:
                default: 8080
                description: Internal HTTP port to use
                type: integer
              resourcePreset:
                description: Resource preset
                enum:
                - small
                - medium
                - large
                type: string
              resources:
                description: Custom resources object - you can use this instead of
                  using the preset.
                properties:
                  cpu:
                    type: string
                  memory:
                    type: string
                required:
                - cpu
                - memory
                type: object
              type:
                default: web
                description: Type of Spring Boot Application
                enum:
                - web
                - webflux
                - native
                type: string
            required:
            - image
            type: object
          status:
            description: SpringBootApplicationStatus defines the observed state of
              SpringBootApplication.
            properties:
              conditions:
                items:
                  description: Condition contains details for one aspect of the current
                    state of this API Resource.
                  properties:
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the transition.
                        This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: |-
                        observedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                        The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
            required:
            - conditions
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
